name: linter

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

permissions:
  contents: write

jobs:
  quality:
    runs-on: ubuntu-latest
    environment: Testing

    env:
      # Matikan semua broadcasting biar Reverb/Pusher tidak aktif
      BROADCAST_DRIVER: log
      REVERB_APP_KEY: dummy
      REVERB_APP_SECRET: dummy
      REVERB_APP_ID: dummy
      REVERB_HOST: localhost
      REVERB_PORT: 6001
      PUSHER_APP_KEY: dummy
      PUSHER_APP_SECRET: dummy
      PUSHER_APP_ID: dummy
      PUSHER_HOST: localhost
      PUSHER_PORT: 6001

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer:v2

      - name: Add Flux Credentials Loaded From ENV
        run: composer config http-basic.composer.fluxui.dev "${{ secrets.FLUX_USERNAME }}" "${{ secrets.FLUX_LICENSE_KEY }}"

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-progress --prefer-dist
          npm install --no-audit --no-fund

      - name: Run Pint
        run: vendor/bin/pint
